[package]
name = "quicksync-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version="4.4.14", features=["derive"] }
duration-string = "0.3.0"
futures-util = "0.3.30"
md5 = "0.7.0"
reqwest = { version = "0.11.23", features = ["json", "stream"] }
rusqlite = "0.30.0"
tokio = { version = "1.35.1", features = ["full"] }
url = "2.5.0"
zip = "0.6.6"
