[package]
name = "quicksync"
version = "0.1.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.31"
clap = { version = "4.5.17", features = ["derive"] }
duration-string = "0.4.0"
md5 = "0.7.0"
regex = "1.10.3"
reqwest = { version = "0.12.7", features = ["json", "stream", "blocking"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
url = "2.5.0"
zstd = "0.13.0"

[dev-dependencies]
mockito = "1.5.0"
rand = "0.8.5"
tempfile = "3.12.0"
